@startuml
class Compra {
    + Compra()
    + Compra(fechaCompra:DateTime, precioTotal:decimal, codigoDescuento:string?)
    + Id : int <<get>> <<set>>
    + FechaCompra : DateTime <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + CodigoDescuento : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}


@enduml