@startuml
class Genero {
    + Genero()
    + Genero(nombre:string)
    + Id : int <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
@enduml
