@startuml
class GooglePay {
    + GooglePay()
    + GooglePay(email:string)
    + Email : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}


@enduml