@startuml
class Libro {
    + Libro()
    + Libro(titulo:string, autor:string, fechaLanzamiento:DateTime, precioCompra:decimal, stock:int, editorialId:int, generoId:int)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Autor : string <<get>> <<set>>
    + FechaLanzamiento : DateTime <<get>> <<set>>
    + PrecioCompra : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + EditorialId : int <<get>> <<set>>
    + GeneroId : int <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}


@enduml




