@startuml
class Resena {
    + Resena()
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + UsuarioId : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
Resena --> "FechaResena" DateTime
@enduml
