@startuml
class Resena {
    + Resena()
    + Id : int <<get>> <<set>>
    + FechaResena : DateTime <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}

Resena --> "Usuario" ApplicationUser
Resena --> "ResenaItems" ResenaItem     
@enduml