@startuml
class SubastaItem {
    + PrecioPuja : decimal <<get>> <<set>>
    + Descripcion : string <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + SubastaId : int <<get>> <<set>>
    + SubastaItem()
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
SubastaItem o-> "Libro" Libro
SubastaItem o-> "Subasta" Subasta
@enduml
