@startuml
class SubastaItem {
    + PrecioPuja : decimal <<get>> <<set>>
    + Descripcion : string? <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + SubastaId : int <<get>> <<set>>
    + SubastaItem()
    + SubastaItem(precioPuja:decimal, descripcion:string?, libroId:int, subastaId:int)
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
@enduml
